name: GRPS1024
version: "0.1"
license: "GPL-2.0-or-later"
date: 2022-06-20
description: |
    Utilities for iterating through the groups of order 1024 with p-class at least 3

authors:
    - name: Burrell David
      url: mailto:davidburrell@ufl.edu

maintainers:
    - name: Burrell David
      url: mailto:davidburrell@ufl.edu

GAP: ">= 4.11"

www: https://TODO/
readme: README.md
packageinfo: https://TODO/PackageInfo.g

downloads:
    - name: .tar.gz
      url: https://TODO//GRPS1024-0.1.tar.gz

abstract: |

status: dev
doc-html: doc/chap0.html
doc-pdf: doc/manual.pdf
citeas: |
    <p class='BibEntry'>
    [<span class='BibKey'>Dav22</span>]   <b class='BibAuthor'>David, B.</b>,
     <i class='BibTitle'>GRPS1024, Utilities for iterating through the groups of order 1024 with p-class at least 3,
             Version 0.1</i>
     (<span class='BibYear'>2022</span>)<br />
    (<span class='BibNote'>GAP package</span>),
    <span class='BibHowpublished'><a href="https://TODO/">https://TODO/</a></span>.
    </p>
    

bibtex: |
    @misc{ GRPS10240.1,
      author =           {David, B.},
      title =            {{GRPS1024}, Utilities for iterating through the groups of order 1024
                          with p-class at least 3, {V}ersion 0.1},
      month =            {Jun},
      year =             {2022},
      note =             {GAP package},
      howpublished =     {\href {https://TODO/} {\texttt{https://TODO/}}},
      printedkey =       {Dav22}
    }

