name: GRPS1024
version: "0.0.1"
license: "GPL-2.0-or-later"
date: 2022-06-20
description: |
    Library of the groups of order 1024 of p-class at least 3, those of p-class two and rank 4 and those of p-class 1 and rank 10.

authors:
    - name: David Burrell
      url: https://davidburrell.github.io/

maintainers:
    - name: David Burrell
      url: https://davidburrell.github.io/

GAP: ">= 4.11"

www: https://davidburrell.github.io/GRPS1024/
readme: README.md
packageinfo: https://davidburrell.github.io/GRPS1024/PackageInfo.g
github: https://github.com/davidburrell/GRPS1024

downloads:
    - name: .tar.gz
      url: https://github.com/davidburrell/GRPS1024/archive/refs/tags/v0.0.1.tar.gz
    - name: .zip
      url: https://github.com/davidburrell/GRPS1024/archive/refs/tags/v0.0.1.zip

abstract: |

status: dev
doc-html: doc/chap0.html
doc-pdf: doc/manual.pdf
citeas: |
    <p class='BibEntry'>
    [<span class='BibKey'>Bur22</span>]   <b class='BibAuthor'>Burrell, D.</b>,
     <i class='BibTitle'>GRPS1024, Library of the groups of order 1024 of p-class at least 3, those of p-class two and rank 4 and those of p-class 1 and rank 10.,
             Version 0.0.1</i>
     (<span class='BibYear'>2022</span>)<br />
    (<span class='BibNote'>GAP package</span>),
    <span class='BibHowpublished'><a href="https://davidburrell.github.io/GRPS1024/">https://davidburrell.github.io/GRPS1024/</a></span>.
    </p>
    

bibtex: |
    @misc{ GRPS10240.0.1,
      author =           {Burrell, D.},
      title =            {{GRPS1024},  Library of the groups of order 1024 of p-class at least
                          3,  those  of p-class two and rank 4 and those of p-class 1 and rank
                          10., {V}ersion 0.0.1},
      month =            {Jun},
      year =             {2022},
      note =             {GAP package},
      howpublished =     {\href                     {https://davidburrell.github.io/GRPS1024/}
                          {\texttt{https://davidburrell.github.io/}\discretionary
                          {}{}{}\texttt{GRPS1024/}}},
      printedkey =       {Bur22}
    }

